name: 'imprint version'
description: 'imprints the version and build time into a source file'
inputs:
  file:
    description: 'the file to imprint into'
    required: true
outputs:
  version:
    description: 'The version being used'
  sha:
    description: 'The github sha value'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}