name: 'imprint version
description: 'imprints the vesion and build time into source file'
inputs:
  version:
    description: 'The version number to imprint'
    required: true
  file:
    description: 'the file to imprint into'
    required: true
outputs:
  time:
    description: 'The time of the operation'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.file }}