name: 'imprint version'
description: 'imprints the version and build time into a source file'
inputs:
  file:
    description: 'the file to imprint into'
    required: true
outputs:
  time:
    description: 'The time of the operation'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }}